### ISSUE TITLE
BUG: Word not rendering

### ISSUE THREAD

**Issue by AntGa** [RuffByte/KeyLabs#26]
# Problem

sometimes the word doesn't render on the screen, leading to the image below:

![image](https://github.com/user-attachments/assets/d3f2054c-4e3b-40c4-b953-1723b1e520a5)

**Comment by tulza** [comment]
> [!IMPORTANT]
> **Bug resolved in** (9c1baeb): this bug occurs when there isn't enough space for more circles to generate.
> usually happens when a large word appears.

 **Fix**
 in `generate-point.ts`, the distance calculation logic have been modified such that the circle minimum distance is dynamic.
 previously, the minimum distance is hard coded to value 2 meaning that the minimum distance between each circles is at least **2 circle perimeter distance** away from each other.

**new:**
 the hard-coded value has now been replaced with a dynamic value labelled `baseDistMultiplier` set to 2 initial,
 once the function has failed to generate points, `baseDistMultiplier` will be decremented by 0.2 each time leaving more spaces for points to generate.
 
![image](https://github.com/user-attachments/assets/32fd6115-f79b-488c-a02b-7f1b2d762506)

**Comment by AntGa** [comment]
![fire](https://c.tenor.com/dxPl_UoR8J0AAAAd/tenor.gif)
